### ISSUE TITLE
Move all microservices to microservices-node-pool with affinity

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-infrastructure#57]
Please update deployment/base/*deployment.yaml in the following repositories to contain node affinity for the new microservices-node-pool

An example can be found here:
https://github.com/Greenstand/treetracker-messaging-api/blob/main/deployment/base/deployment.yaml

The affinity block looks like:
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool

```
The microservices repos are
https://github.com/Greenstand/treetracker-api
https://github.com/Greenstand/treetracker-earnings
https://github.com/Greenstand/treetracker-admin-api
https://github.com/Greenstand/treetracker-wallet-api
https://github.com/Greenstand/treetracker-field-data
https://github.com/Greenstand/treetracker-web-map-api
https://github.com/Greenstand/bulk-pack-consumer
https://github.com/Greenstand/bulk-pack-transformer
https://github.com/Greenstand/webmap-query-service-consumer

Please submit changes as a PR to each of these repositories.

The commit message should be
feat: move deployment to microservices-node-pool
